apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kjayd6vzr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kjayd6vzr-go 
  name: kjayd6vzr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kjayd6vzr-go 
